var age = 25;
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'patrick' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('patrick');
mixed.push(false);
console.log(mixed);
var dev;
dev = { name: 'patrick', age: 20 };
console.log(dev);
dev = { age: 25, name: 'robert' };
console.log(dev);
